# This workflow will build a Playwright Java test project with Maven.


# Steps
# 1. Check out the repository
# 2. Set up JDK 22
# 3. Build with Maven
# 4. Run tests
# 5. Load test report history
# 6. Build test report
# 7. Publish test report

name: CI and Deploy

on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: maven

      - name: Build with Maven
        run: mvn -q -B compile --file pom.xml


      - name: Run tests Api Regression
        run: mvn -q -B clean test -Dgroups=API_Regression

      - name: Run tests regression
        run: mvn -q -B clean test -Dgroups=regression

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
