# This workflow will build a Playwright Java test project with Maven.

# Steps
# 1. Check out the repository
# 2. Set up JDK 22
# 3. Build with Maven
# 4. Run tests
# 5. Load test report history
# 6. Build test report
# 7. Publish test report

name: CI and Deploy

on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-ra
    steps:
      - uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn -B compile --file pom.xml


      - name: Run tests Api Regression
        run: mvn -B clean test -Dgroups=API_Regression

      - name: Run tests regression
        run: mvn -B clean test -Dgroups=regression
        
      - name: Run tests end-to-end
        run: mvn -B test -Dtest="e2e.tests.LoginTest"
        
      - name: Run tests end-to-end
        run: mvn -B test -Dtest="e2e.tests.ProductPage"

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

