# This workflow will build a Playwright Java test project with Maven.

# Steps
# 1. Check out the repository
# 2. Set up JDK 22
# 3. Build with Maven
# 4. Run tests
# 5. Load test report history
# 6. Build test report
# 7. Publish test report

name: CI and Deploy

on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-ra
    steps:
      - uses: actions/checkout@v4

      - name: Build Web Application
        run: echo "Building Web Application"

      - name: Build with Maven
        run: mvn -B compile --file pom.xml
        
      - name: Run tests Api Regression and Regression
        run: mvn -B test -Dgroups="API_Regression,regression"
        
      - name: Run E2E tests (LoginTest and ProductTest)
        run: mvn -B test -Dtest="e2e.tests.LoginTest,e2e.tests.ProductTest"

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy allure results to gh-pages
        run: |
          xcopy /E /Y target\allure-results gh-pages\allure-results\
        shell: cmd

      - name: Commit and push allure results
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add allure-results
          git commit -m "Update allure-results from run #${{ github.run_number }}"
          git push origin gh-pages
        shell: cmd
        
      - name: Deploy Web Application
        run: echo "Deploy Web Application"

